"""
Database models and session management.
"""
from datetime import datetime, timezone
from sqlalchemy import (
    Column,
    DateTime,
    Integer,
    String,
    Text,
    JSON,
    Boolean,
)
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import declarative_base, sessionmaker

from config import settings

engine = create_async_engine(settings.database_url, echo=False)
async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

Base = declarative_base()


def _utcnow():
    return datetime.now(timezone.utc)


class Conversation(Base):
    """A single conversation turn between user and AI child."""

    __tablename__ = "conversations"

    id = Column(Integer, primary_key=True, index=True)
    role = Column(String(16), nullable=False)  # "user" | "assistant"
    content = Column(Text, nullable=False)
    content_type = Column(String(32), default="text")  # text | image | audio | mixed
    media_path = Column(String(512), nullable=True)  # path to saved media file
    timestamp = Column(DateTime(timezone=True), default=_utcnow)
    metadata_ = Column("metadata", JSON, default=dict)


class KnowledgeItem(Base):
    """Explicit knowledge taught by the user."""

    __tablename__ = "knowledge"

    id = Column(Integer, primary_key=True, index=True)
    topic = Column(String(256), nullable=False, index=True)
    content = Column(Text, nullable=False)
    source = Column(String(64), default="user")  # "user" | "self"
    confidence = Column(Integer, default=100)  # 0-100
    timestamp = Column(DateTime(timezone=True), default=_utcnow)
    last_reviewed = Column(DateTime(timezone=True), nullable=True)


class PendingQuestion(Base):
    """Questions the AI child wants to ask the user."""

    __tablename__ = "pending_questions"

    id = Column(Integer, primary_key=True, index=True)
    question = Column(Text, nullable=False)
    topic = Column(String(256), nullable=True)
    answered = Column(Boolean, default=False)
    answer = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), default=_utcnow)
    answered_at = Column(DateTime(timezone=True), nullable=True)


class Tool(Base):
    """A reusable Python tool created by the AI child."""

    __tablename__ = "tools"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(128), nullable=False, unique=True, index=True)
    description = Column(Text, nullable=False)
    code = Column(Text, nullable=False)
    # OpenAI-style JSON schema describing the tool's parameters
    parameters_schema = Column(JSON, nullable=False, default=dict)
    call_count = Column(Integer, default=0)
    created_at = Column(DateTime(timezone=True), default=_utcnow)


class AIProfile(Base):
    """
    Singleton row (id=1) holding the AI child's personal profile.

    The AI starts unnamed.  Its very first proactive question asks the user
    what to call it.  Once the user replies, `name` is set permanently.
    """

    __tablename__ = "ai_profile"

    id = Column(Integer, primary_key=True, default=1)
    name = Column(String(128), nullable=True)          # None until named
    created_at = Column(DateTime(timezone=True), default=_utcnow)
    named_at = Column(DateTime(timezone=True), nullable=True)
    # Sleep state
    is_sleeping = Column(Boolean, default=False)
    last_consolidation_summary = Column(Text, nullable=True)
    # Localization
    preferred_language = Column(String(16), default="en-US")  # "en-US" | "zh-CN"
    # Personality traits (structured data)
    personality_traits = Column(JSON, default=dict)  # {"interests": [], "values": [], "quirks": []}


class SleepEvent(Base):
    """
    A sleep or wake notification generated by the AI child's sleep scheduler.

    The bot polls for unconsumed events and pushes them to all connected chats.
    """

    __tablename__ = "sleep_events"

    id = Column(Integer, primary_key=True, index=True)
    event_type = Column(String(16), nullable=False)    # "sleep" | "wake"
    message = Column(Text, nullable=True)              # personalised GPT message
    consumed = Column(Boolean, default=False)          # True once bot has delivered it
    created_at = Column(DateTime(timezone=True), default=_utcnow)


class PersonalityMemory(Base):
    """
    Explicit personality-shaping memories that define the AI child's character.
    
    These are NOT subject to automatic deletion. They're foundational to the AI's identity.
    Separate from regular memories for intentional curation and easy backup/export.
    
    Example categories:
    - personality_traits: What makes this AI unique
    - values: What the AI cares about (e.g., curiosity, kindness)
    - origin_story: How the AI came to be
    - important_relationships: Key connections with users
    - core_beliefs: Philosophical stance (neutral as assistant, but has personal views)
    """

    __tablename__ = "personality_memories"

    id = Column(Integer, primary_key=True, index=True)
    category = Column(String(64), nullable=False, index=True)  # "traits" | "values" | "origin" | "relationships" | "beliefs"
    content = Column(Text, nullable=False)                      # The memory itself
    significance = Column(Integer, default=100)                 # 1-100, higher = more fundamental
    source = Column(String(32), default="user")                 # "user" | "self" | "system" | "web"
    source_authority = Column(Integer, default=100)             # Source weight: user=100, verified_web=70, web=40, inference=50
    is_neutral_fact = Column(Boolean, default=False)            # True = neutral assistant info, False = personality stance
    is_stance_relevant = Column(Boolean, default=True)          # False = web data won't influence AI's stance/personality
    created_at = Column(DateTime(timezone=True), default=_utcnow)
    last_reviewed_at = Column(DateTime(timezone=True), nullable=True)
    verified_at = Column(DateTime(timezone=True), nullable=True)  # When the memory was verified/reviewed
    # Metadata for better organization
    tags = Column(JSON, default=list)  # ["important", "core", "verified", "web:caution"]
    context = Column(Text, nullable=True)  # Additional context or explanation


async def init_db():
    """Create all tables if they do not exist."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


async def get_session():
    """FastAPI dependency that provides a database session."""
    async with async_session() as session:
        yield session
