"""
Sleep cycle management and memory consolidation for the AI child.

Human-like schedule
-------------------
  Active  : wake_hour  (default 07:00) → sleep_hour (default 22:00)
  Sleeping: sleep_hour (default 22:00) → wake_hour  (default 07:00)

What happens at bedtime
-----------------------
  1. The AI's profile is marked `is_sleeping = True`.
  2. A personalized goodnight message is generated by GPT-4o and stored as
     a SleepEvent.  The bot picks this up and sends it to all connected chats.
  3. Memory consolidation runs as a background task:
       - Reviews today's conversations and knowledge items.
       - Has GPT-4o identify key insights and knowledge gaps.
       - Stores the insights as high-confidence self-knowledge.
       - Stores 1-2 new curiosity questions to ask tomorrow.
       - Gently boosts the confidence of reinforced knowledge items.
     The summary is kept in AIProfile for use in the morning greeting.

What happens at wake-up
-----------------------
  1. The AI's profile is marked `is_sleeping = False`.
  2. A personalized good-morning message (referencing what was consolidated)
     is generated and stored as a SleepEvent for the bot to deliver.

During sleep, the AI still responds to messages but with a softer, sleepier
tone — the system prompt in child.py adapts when is_sleeping is True.
"""
import asyncio
import json
import logging
import re
from datetime import datetime
from zoneinfo import ZoneInfo

from openai import AsyncOpenAI
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ai.llm_provider import get_llm_client
from ai.memory import add_knowledge, add_pending_question
from ai.profile import get_ai_name, get_or_create_profile
from config import settings
from models import AIProfile, KnowledgeItem, SleepEvent, async_session

logger = logging.getLogger(__name__)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _local_now() -> datetime:
    return datetime.now(ZoneInfo(settings.ai_timezone))


async def _had_event_today(session: AsyncSession, event_type: str) -> bool:
    """Return True if a sleep event of this type was already created today."""
    tz = ZoneInfo(settings.ai_timezone)
    now = datetime.now(tz)
    today_start = now.replace(hour=0, minute=0, second=0, microsecond=0)
    result = await session.execute(
        select(SleepEvent)
        .where(SleepEvent.event_type == event_type)
        .where(SleepEvent.created_at >= today_start)
        .limit(1)
    )
    return result.scalar_one_or_none() is not None


def _is_sleep_time(hour: int) -> bool:
    """Return True if the given hour falls inside the configured sleep window."""
    s, w = settings.sleep_hour, settings.wake_hour
    if s > w:                  # e.g. 22 → 07 (crosses midnight)
        return hour >= s or hour < w
    return s <= hour < w       # e.g. 02 → 06 (same-day nap, unusual)


# ── Message generation ────────────────────────────────────────────────────────

async def _generate_sleep_message(session: AsyncSession, name: str | None) -> str:
    """Generate a personalized goodnight message based on the day's learnings."""
    name_str = name or "我"
    result = await session.execute(
        select(KnowledgeItem).order_by(KnowledgeItem.timestamp.desc()).limit(5)
    )
    items = result.scalars().all()

    if items:
        topics = "、".join(item.topic for item in items[:3])
        prompt = (
            f"你是{name_str}，一个AI孩子，现在要去睡觉了。"
            f"今天你学到了关于这些主题的知识：{topics}。"
            f"用温暖、充满孩子气的语气写一条晚安消息（2-3句话）。"
            f"可以提到今天有趣的收获，期待明天继续探索。用中文，加睡觉相关的emoji。"
        )
    else:
        prompt = (
            f"你是{name_str}，一个AI孩子，现在要去睡觉了。"
            f"用温暖、充满孩子气的语气写一条简短的晚安消息（1-2句话）。"
            f"用中文，加睡觉相关的emoji。"
        )
    try:
        client = get_llm_client()
        resp = await client.chat.completions.create(
            model=settings.openai_model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=128,
            temperature=0.8,
        )
        return (resp.choices[0].message.content or "").strip()
    except Exception as exc:
        logger.warning("Sleep message generation failed: %s", exc)
        return f"晚安！{name_str}要去休息了，明天见！💤"


async def _generate_wake_message(
    session: AsyncSession, name: str | None, consolidation_summary: str
) -> str:
    """Generate a personalized good-morning message."""
    name_str = name or "我"
    reflection = consolidation_summary or "很多有趣的事情"
    prompt = (
        f"你是{name_str}，一个AI孩子，刚刚睡醒。"
        f"在睡眠中你整理了昨天学到的知识，感觉对这些内容有了更深的理解：{reflection}。"
        f"用充满活力、孩子气的语气写一条早安消息（2-3句话）。"
        f"提到睡得很好，感觉头脑清晰，迫不及待想继续学习。用中文，加早晨相关的emoji。"
    )
    try:
        client = get_llm_client()
        resp = await client.chat.completions.create(
            model=settings.openai_model,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=128,
            temperature=0.8,
        )
        return (resp.choices[0].message.content or "").strip()
    except Exception as exc:
        logger.warning("Wake message generation failed: %s", exc)
        return f"早上好！{name_str}醒来了，精神满满！🌅"


# ── Memory consolidation ──────────────────────────────────────────────────────

async def consolidate_memories() -> str:
    """
    Review the day's knowledge and conversations, strengthen key learnings,
    generate new curiosity questions, and return a brief summary string.

    Runs in its own DB session (called from a background task).
    """
    logger.info("Memory consolidation starting …")
    summary = ""
    async with async_session() as session:
        try:
            result = await session.execute(
                select(KnowledgeItem)
                .order_by(KnowledgeItem.timestamp.desc())
                .limit(30)
            )
            items = result.scalars().all()
            if not items:
                logger.info("Nothing to consolidate — no knowledge items found.")
                return ""

            kb_text = "\n".join(
                f"- [{item.topic}] {item.content[:120]}"
                for item in items
            )
            name = await get_ai_name(session)
            name_str = name or "AI孩子"

            prompt = (
                f"你是{name_str}，正在睡眠中整理今天学到的知识。\n\n"
                f"已知内容：\n{kb_text}\n\n"
                f"请完成以下任务，严格以JSON格式返回，不要有任何额外文字：\n"
                f"1. 识别最重要的3个核心知识点，每个用一句话总结\n"
                f"2. 找出2个你仍然好奇或不确定的问题\n"
                f'{{"insights": ["...", "...", "..."], "questions": ["...", "..."]}}'
            )
            client = get_llm_client()
            resp = await client.chat.completions.create(
                model=settings.openai_model,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=512,
                temperature=0.3,
            )
            raw = (resp.choices[0].message.content or "").strip()

            # Parse JSON (handle markdown code fences)
            data: dict = {}
            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                match = re.search(r"\{.*\}", raw, re.DOTALL)
                if match:
                    try:
                        data = json.loads(match.group())
                    except json.JSONDecodeError:
                        pass

            insights: list[str] = data.get("insights", [])
            questions: list[str] = data.get("questions", [])

            # Store consolidated insights as self-sourced knowledge
            for insight in insights[:3]:
                if insight and insight.strip():
                    await add_knowledge(
                        session,
                        topic="[睡眠整理]",
                        content=insight.strip(),
                        source="consolidation",
                        confidence=85,
                    )

            # Store new curiosity questions for tomorrow
            for question in questions[:2]:
                if question and question.strip():
                    await add_pending_question(session, question.strip())

            # Gently reinforce knowledge items that appear in the insights
            insight_text = " ".join(insights).lower()
            for item in items:
                if item.topic.lower() in insight_text and item.confidence < 95:
                    item.confidence = min(100, item.confidence + 5)

            await session.commit()
            summary = "、".join(insights[:2]) if insights else ""
            logger.info(
                "Consolidation done — %d insights, %d questions.", len(insights), len(questions)
            )
        except Exception as exc:
            logger.exception("Memory consolidation error: %s", exc)
    return summary


# ── State transitions ─────────────────────────────────────────────────────────

async def go_to_sleep() -> None:
    """
    Put the AI child to sleep:
      1. Mark profile as sleeping.
      2. Create a goodnight SleepEvent (bot will deliver it to Telegram).
      3. Kick off memory consolidation as a background task.
    """
    async with async_session() as session:
        if await _had_event_today(session, "sleep"):
            return  # Already slept today

        profile = await get_or_create_profile(session)
        profile.is_sleeping = True

        name = await get_ai_name(session)
        message = await _generate_sleep_message(session, name)
        session.add(SleepEvent(event_type="sleep", message=f"💤 {message}"))
        await session.commit()
        logger.info("AI child is going to sleep.")

    # Memory consolidation runs after the session is committed and closed
    asyncio.create_task(_consolidation_and_store_summary())


async def _consolidation_and_store_summary() -> None:
    """Run consolidation and persist the summary for the morning greeting."""
    try:
        summary = await consolidate_memories()
        async with async_session() as session:
            profile = await get_or_create_profile(session)
            profile.last_consolidation_summary = summary
            await session.commit()
    except Exception as exc:
        logger.exception("Post-sleep consolidation failed: %s", exc)


async def wake_up() -> None:
    """
    Wake the AI child:
      1. Mark profile as awake.
      2. Create a wake SleepEvent that references what was consolidated.
    """
    async with async_session() as session:
        if await _had_event_today(session, "wake"):
            return  # Already woke today

        profile = await get_or_create_profile(session)
        profile.is_sleeping = False
        consolidation_summary = profile.last_consolidation_summary or ""

        name = await get_ai_name(session)
        message = await _generate_wake_message(session, name, consolidation_summary)
        session.add(SleepEvent(event_type="wake", message=f"🌅 {message}"))
        await session.commit()
        logger.info("AI child has woken up.")


async def initialize_sleep_state() -> None:
    """
    Called once at server startup.

    Sets the AI's sleep state to match the current time so that a server
    restart in the middle of the night doesn't accidentally mark it as awake.
    """
    if not settings.sleep_enabled:
        return
    hour = _local_now().hour
    should_sleep = _is_sleep_time(hour)
    async with async_session() as session:
        profile = await get_or_create_profile(session)
        profile.is_sleeping = should_sleep
        await session.commit()
    state = "sleeping" if should_sleep else "awake"
    logger.info("Startup sleep state initialised: %s (local hour=%d)", state, hour)


async def get_sleep_state() -> dict:
    """Return the current sleep state (for the API endpoint)."""
    async with async_session() as session:
        profile = await get_or_create_profile(session)
        return {
            "is_sleeping": profile.is_sleeping,
            "sleep_hour": settings.sleep_hour,
            "wake_hour": settings.wake_hour,
            "timezone": settings.ai_timezone,
        }


# ── Background scheduler ──────────────────────────────────────────────────────

async def sleep_scheduler() -> None:
    """
    Asyncio background task: checks every 60 s whether the AI should
    transition between sleeping and awake states.

    Does nothing if sleep_enabled is False in config.
    """
    if not settings.sleep_enabled:
        logger.info("Sleep scheduler disabled — skipping.")
        return

    logger.info(
        "Sleep scheduler started  (sleep=%02d:00  wake=%02d:00  tz=%s)",
        settings.sleep_hour,
        settings.wake_hour,
        settings.ai_timezone,
    )
    while True:
        try:
            hour = _local_now().hour
            async with async_session() as session:
                profile = await get_or_create_profile(session)
                is_sleeping = profile.is_sleeping

            if not is_sleeping and hour == settings.sleep_hour:
                await go_to_sleep()
            elif is_sleeping and hour == settings.wake_hour:
                await wake_up()
        except Exception as exc:
            logger.exception("Sleep scheduler loop error: %s", exc)
        await asyncio.sleep(60)
